# Generated by Django 4.1.4 on 2022-12-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('pais', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=50)),
            ],
        ),
    ]
