# Generated by Django 4.1.4 on 2022-12-17 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('pais', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('grupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('marcador1', models.CharField(max_length=2)),
                ('marcador2', models.CharField(max_length=2)),
                ('fecha', models.DateField()),
                ('equipos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Partidos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('codigo_apuesta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marcador1', models.CharField(max_length=2)),
                ('marcador2', models.CharField(max_length=2)),
                ('monto', models.CharField(max_length=50)),
                ('codigo_partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Partidos.partido')),
            ],
        ),
    ]
