# Generated by Django 4.1.4 on 2022-12-18 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Partidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='equipos2',
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipos1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_equipos1', to='Partidos.equipo'),
        ),
    ]
